import { assets } from "../../assets/assets"

// --- CATEGORIES DATA ---
export const categories = {
  Books: {
    subcategories: ["Munzereen Shahid", "Sadat Hossain", "Humayun Ahmed"],
    filters: ["topic"],
    topics: ["Educational", "Fiction", "History", "Adventure", "Religious"],
  },
  Clothes: {
    subcategories: ["Jamdani", "Panjabi", "Benaroshi", "Kurta", "Kids Clothes"],
    filters: ["size", "color", "origin"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red", "Blue", "Green", "Yellow", "Black", "White", "Pink"],
    origins: ["Tangail", "Dhakaiya", "Sylhet", "Chittagong"],
  },
  Ornaments: {
    subcategories: ["Earring", "Necklace", "Bracelets", "Ring", "Payel"],
    filters: ["material", "size"],
    materials: ["Gold", "Silver", "Bronze", "Earthen", "Iron"],
    sizes: ["S", "M", "L", "XL"],
  },
}

// --- SAMPLE PRODUCTS DATA (CRITICAL: UPDATED SIZE TO ARRAY) ---
export const sampleProducts = [
    {
      id: 1,
      name: "সবার জন্য VOCABULARY",
      category: "Books",
      subcategory: "Munzereen Shahid",
      author: "Munzereen Shahid",
      price: 550,
      originalPrice: 650,
      rating: 5.0,
      reviews: 10,
      inStock: true,
      image: assets.jukti_fade_foring,
      topic: "Educational",
      sale: false,
      isBestSeller: true,
      description:
        "A comprehensive vocabulary building guide designed for learners of all levels. This book provides systematic approaches to expanding your English vocabulary with practical examples, exercises, and memory techniques. Perfect for students preparing for competitive exams or anyone looking to enhance their language skills.",
    },
    {
      id: 2,
      name: "ঘরে বসে SPOKEN ENGLISH",
      category: "Books",
      subcategory: "Munzereen Shahid",
      author: "Munzereen Shahid",
      price: 350,
      originalPrice: 400,
      rating: 5.0,
      reviews: 10,
      inStock: false,
      image: assets.ferari_rajputro,
      topic: "Educational",
      sale: false,
      isBestSeller: true,
      description:
        "Master spoken English from the comfort of your home with this practical guide. Features conversational patterns, common phrases, pronunciation tips, and real-life dialogue examples. Includes audio references and interactive exercises to build confidence in speaking English fluently.",
    },
    {
      id: 3,
      name: "ঘরে বসে IELTS প্রস্তুতি",
      category: "Books",
      subcategory: "Munzereen Shahid",
      author: "Munzereen Shahid",
      price: 400,
      originalPrice: 500,
      rating: 5.0,
      reviews: 10,
      inStock: true,
      image: assets.pother_golpo,
      topic: "Educational",
      sale: true,
      isBestSeller: true,
      description:
        "Complete IELTS preparation guide covering all four modules: Listening, Reading, Writing, and Speaking. Includes practice tests, scoring strategies, time management tips, and expert advice for achieving your target band score. Ideal for self-study with detailed answer explanations.",
    },
    {
      id: 10,
      name: "নক্ষত্রের রাত",
      category: "Books",
      subcategory: "Humayun Ahmed",
      author: "Humayun Ahmed",
      price: 450,
      originalPrice: 550,
      rating: 4.5,
      reviews: 20,
      inStock: true,
      image: assets.jukti_fade_foring,
      topic: "Fiction",
      sale: false,
      isBestSeller: true,
      description:
        "A captivating novel by the legendary Humayun Ahmed that weaves together romance, mystery, and human emotions under the starlit sky. This beautifully written story explores the complexities of relationships and the magic of unexpected encounters. A must-read for fans of Bengali literature.",
    },
    {
      id: 4,
      name: "Classic Panjabi",
      category: "Clothes",
      subcategory: "Panjabi",
      price: 1200,
      originalPrice: 1500,
      rating: 4.5,
      reviews: 35,
      inStock: true,
      image: assets.G12,
      size: ["S","M","L","XL"],
      color: "Green",
      origin: "Dhakaiya",
      sale: true,
      isBestSeller: true,
      description:
        "Elegant traditional Panjabi crafted with premium quality fabric from Dhaka. Features intricate embroidery and classic design perfect for festive occasions and cultural celebrations. Made with breathable cotton blend for all-day comfort. Authentic Dhakaiya craftsmanship with modern tailoring.",
    },
    {
      id: 5,
      name: "Cotton Kurta",
      category: "Clothes",
      subcategory: "Kurta",
      price: 900,
      originalPrice: 1100,
      rating: 4.0,
      reviews: 22,
      inStock: true,
      image: assets.G13,
      size: ["S","M","L","XL"],
      color: "Green",
      origin: "Tangail",
      sale: false,
      isBestSeller: true,
      description:
        "Comfortable and stylish cotton kurta from Tangail, perfect for casual and semi-formal occasions. Made from 100% pure cotton with excellent breathability and durability. Features a contemporary cut with traditional elements. Easy to maintain and suitable for year-round wear.",
    },
    {
      id: 6,
      name: "Kids Festive Dress",
      category: "Clothes",
      subcategory: "Jamdani",
      price: 700,
      originalPrice: 850,
      rating: 4.8,
      reviews: 18,
      inStock: true,
      image: assets.Bl9,
      size: ["S","M","L","XL"],
      color: "Blue",
      origin: "Dhakaiya",
      sale: true,
      isBestSeller: true,
      description:
        "Adorable festive dress for kids featuring beautiful Jamdani patterns in vibrant blue. Handwoven with soft, child-friendly fabric that ensures comfort throughout celebrations. Traditional Dhakaiya design with modern styling. Perfect for Eid, weddings, and special occasions.",
    },
    {
      id: 7,
      name: "Elegant Gold Necklace",
      category: "Ornaments",
      subcategory: "Necklace",
      price: 2500,
      originalPrice: 3000,
      rating: 5.0,
      reviews: 40,
      inStock: true,
      image: assets.Goldnecklace,
      material: "Gold",
      size: ["S","M","L","XL"],
      sale: true,
      isBestSeller: true,
      description:
        "Exquisite gold-plated necklace featuring traditional Bengali design with intricate detailing. Crafted by skilled artisans using high-quality materials for lasting shine and durability. Perfect for weddings, parties, and special occasions. Comes with anti-tarnish coating and elegant packaging.",
    },
    {
      id: 8,
      name: "Elegant Earthen Necklace",
      category: "Ornaments",
      subcategory: "Necklace",
      price: 2500,
      originalPrice: 3000,
      rating: 5.0,
      reviews: 40,
      inStock: true,
      image: assets.Earthennecklace,
      material: "Earthen",
      size: ["S","M","L","XL"],
      sale: true,
      isBestSeller: true,
      description:
        "Unique handcrafted earthen necklace showcasing traditional terracotta artistry. Each piece is individually made by local artisans, making it one-of-a-kind. Eco-friendly and lightweight, perfect for those who appreciate sustainable fashion. Adds a rustic, ethnic charm to any outfit.",
    },
    {
      id: 9,
      name: "Elegant Silver Necklace",
      category: "Ornaments",
      subcategory: "Necklace",
      price: 2500,
      originalPrice: 3000,
      rating: 5.0,
      reviews: 40,
      inStock: true,
      image: assets.SilverNecklace,
      material: "Silver",
      size: ["S","M","L","XL"],
      sale: true,
      isBestSeller: true,
      description:
        "Stunning silver necklace with contemporary design and traditional motifs. Made from premium quality silver with oxidized finish for an antique look. Hypoallergenic and suitable for sensitive skin. Versatile piece that complements both traditional and modern attire.",
    },
  ]